git clone git@github.com:codemucker/codemucker-parent.git
git clone git@github.com:codemucker/codemucker-lang.git
git clone git@github.com:codemucker/codemucker-jpattern.git
git clone git@github.com:codemucker/codemucker-jmatch.git
git clone git@github.com:codemucker/codemucker-jfind.git
git clone git@github.com:codemucker/codemucker-jtest.git
git clone git@github.com:codemucker/codemucker-testserver.git
git clone git@github.com:codemucker/codemucker-jmutate.git
git clone git@github.com:codemucker/codemucker-testfirst.git
